// <auto-generated />
namespace MvcMusicStudio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20151113_1624 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20151113_1624));
        
        string IMigrationMetadata.Id
        {
            get { return "201511130624162_20151113_1624"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
